apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.2"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: cnpg-system
      interval: 1m
