apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 5m
  chart:
    spec:
      chart: coder
      version: "2.20.0"
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: coder
      interval: 1m
  values:
    coder:
      service:
        type: ClusterIP
      ingress:
        enable: true
        className: nginx
        host: coder.codehenry.de
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls:
          enable: true
          secretName: coder.codehenry.de-tls
      env:
        - name: CODER_ACCESS_URL
          value: "https://coder.codehenry.de"
