apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: '25.28.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    server:
      persistentVolume:
        enabled: true
        size: 8Gi
      global:
        scrape_interval: 15s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-adapter
      version: '4.11.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
