apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/coder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
