apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mongo-community-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/mongodb-community-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
