apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: identitiy-provider
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: "2025.2.2"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: identitiy-provider
      interval: 1m
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - accounts.codehenry.de
        tls:
          - secretName: accounts.codehenry.de-tls
            hosts:
              - accounts.codehenry.de

    postgresql:
      enabled: false
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
      replica:
        replicaCount: 1

  valuesFrom:
    - kind: Secret
      name: authentik-db-app
      valuesKey: username
      targetPath: authentik.postgresql.user

    - kind: Secret
      name: authentik-db-app
      valuesKey: password
      targetPath: authentik.postgresql.password

    - kind: Secret
      name: authentik-db-app
      valuesKey: dbname
      targetPath: authentik.postgresql.name

    - kind: Secret
      name: authentik-db-app
      valuesKey: host
      targetPath: authentik.postgresql.host

    - kind: Secret
      name: authentik-db-app
      valuesKey: port
      targetPath: authentik.postgresql.port

    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
