apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: identitiy-provider
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:4hNQ7GBFeXSrou0iyjq32BJWdREPXfnqDgmXd1Nitx0A/GXryRUIw3hr2W9xgNdXwLr9ZZu67qnttVG0BAbGOljvEnroPXbjumf1eBc2qoQ=,iv:8ewmg8MDhlXiGaXL02roEBQ+XBMAzTbxLQx/kdgfI6w=,tag:dDa9nzW06954oho7kBjHFw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1sa224kdq8x9qvne5nhcgn074xtkcytvn9nje6sjm0rhs5p5lr59svncpgu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaWRMWXptSG9JVURKL0c3
        U0xteXY3WERhanRTV2M0NFVDeFM5a2VZUUN3CmNEMkZxYWVudU1pL29MVXNUYi9v
        dk1TQzZCelAydkE0c2t1emtDek8yZm8KLS0tIFNTSExPOTROV2FMUzFXVEVCUzR2
        MlFiYUlhM1BqL29OTnNDMnN6NEpXVkEKQkuqqqXKeRlFN13I1YB1HpOtxAzesamG
        dEBeBtkmH01dhJBJE7q4EQD/PBH0le9tCeezNUCQmxKhd0itvtInYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-27T19:34:39Z"
  mac: ENC[AES256_GCM,data:Z72K2Acs+8Tx+V6hWjjknzO9TBr32eJHRJv1EDxSnuU7l7l0UrFA2EVhtL/Hc0zVVREBU58W5jnwajFmIAeGmC8WBr1Tgs1NmT6JduxwBK9C7wpMDDI4Jv5TTMeO6YhOdpi3rs1YdTA6bN8tswM5OhSrKaScLQ7OdU1ManUQsPQ=,iv:UXlelfAXihv+LZ5LAd34+s8G3cPGGY4jE1ZDf+saFqI=,tag:GrDKez4DthiTx5mtbTR9EQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
