name: Lint Manifests
on:
  push:
  pull_request:

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Validate YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
