apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: community-operator
  namespace: mongo-system
spec:
  interval: 5m
  chart:
    spec:
      chart: community-operator
      version: "0.12.1"
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: mongo-system
      interval: 1m
  values:
    operator:
      watchNamespace: "*"
